name       : perl-term-table
version    : '0.016'
release    : 6
source     :
    - https://cpan.metacpan.org/authors/id/E/EX/EXODIST/Term-Table-0.016.tar.gz : 8fb4fbb8e96a2d6c514949eb8cfd7e66319bcb1cbf7cea0ab19af887a72d97bf
homepage   : https://metacpan.org/pod/Term::Table
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : Term::Table - Format a header and rows into a table
description: |
    This is used by some failing tests to provide diagnostics about what has gone wrong. This module is able to generic format rows of data into tables.
builddeps  :
    - perl-importer
    - perl-test-simple
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
