name       : perl-term-table
version    : 0.012
release    : 3
source     :
    - https://cpan.metacpan.org/authors/id/E/EX/EXODIST/Term-Table-0.012.tar.gz : 4db6118fbf862bd32a8402e1ee28ce2044d0e0887ef29b726e917ab4258a063a
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : Term::Table - Format a header and rows into a table
description: |
    This is used by some failing tests to provide diagnostics about what has gone wrong. This module is able to generic format rows of data into tables.
builddeps  :
    - perl-importer
    - perl-test-simple
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
